'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var PlayerSchema = new Schema({
    "first" : String,
    "last" : String,
    "position" : String,
    "jersey" : String,
    "overallrating" : String,
    "speed" : String,
    "acceleration" : String,
    "strength" : String,
    "agility" : String,
    "awareness" : String,
    "catching" : String,
    "carrying" : String,
    "throwpower" : String,
    "kickpower" : String,
    "kickaccuracy" : String,
    "runblock" : String,
    "passblock" : String,
    "tackle" : String,
    "jumping" : String,
    "return" : String,
    "injury" : String,
    "stamina" : String,
    "toughness" : String,
    "trucking" : String,
    "elusiveness" : String,
    "bcvision" : String,
    "stiffarm" : String,
    "spinmove" : String,
    "jukemove" : String,
    "impactblock" : String,
    "powermove" : String,
    "finesseemove" : String,
    "blockshedding" : String,
    "pursuit" : String,
    "playrec" : String,
    "mancoverage" : String,
    "zonecoverage" : String,
    "spectacularcatch" : String,
    "catchintraffic" : String,
    "routerunning" : String,
    "hitpower" : String,
    "press" : String,
    "release" : String,
    "throwaccuracyshort" : String,
    "throwaccuracymed" : String,
    "throwaccuracydeep" : String,
    "playaction" : String,
    "throwonrun" : String,
    "team" : String
});

module.exports = mongoose.model('Player', PlayerSchema);